name: macOS Test

on:
  pull_request:
    branches: [master]

jobs:
  test_on_pull_request:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 13
      - run: npm ci
      - run: npm test
        env:
          TGENPATH: '/Users/runner/runners/2.165.2/work/tgen/tgen'
      - run: npm run build